"""empty message

Revision ID: 3ec507e33e28
Revises: 848d9193038c
Create Date: 2024-09-17 11:19:40.062182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec507e33e28'
down_revision = '848d9193038c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planeta_favorito', sa.Integer(), nullable=True),
    sa.Column('personajes_favorito', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personajes_favorito'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planeta_favorito'], ['planeta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorito')
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.drop_column('climate')

    op.create_table('favorito',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorito_pkey')
    )
    op.drop_table('favoritos')
    # ### end Alembic commands ###
