"""empty message

Revision ID: 848d9193038c
Revises: 6d0aeffb1126
Create Date: 2024-09-17 10:45:14.021462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848d9193038c'
down_revision = '6d0aeffb1126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planeta')
    op.drop_table('personajes')
    op.drop_table('favorito')
    # ### end Alembic commands ###
