"""empty message

Revision ID: dba68cfb2d64
Revises: 3ec507e33e28
Create Date: 2024-09-17 15:32:41.927280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba68cfb2d64'
down_revision = '3ec507e33e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('climate', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planeta')
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint('favoritos_planeta_favorito_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planetas', ['planeta_favorito'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_planeta_favorito_fkey', 'planeta', ['planeta_favorito'], ['id'])

    op.create_table('planeta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planeta_pkey')
    )
    op.drop_table('planetas')
    # ### end Alembic commands ###
